---
- name: Ensure that ntp is not installed
  become: True
  package:
    name: ntp
    state: absent

- name: Configure systemd-timesyncd.service
  become: True
  template:
    src: timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf
    mode: 0644
    owner: root
    group: root
  notify: time configuration changed

- name: Start and enable systemd-timesyncd.service
  become: True
  service:
    name: systemd-timesyncd.service
    enabled: yes
    state: started
