---

- name: Update timezone data
  become: True
  command: /usr/sbin/dpkg-reconfigure --frontend noninteractive tzdata
  listen: time configuration changed

- name: Restart systemd-timesyncd.service
  become: True
  service:
    name: systemd-timesyncd.service
    state: restarted
  when: ansible_service_mgr == "systemd"
  listen: time configuration changed

- name: Set HW clock (physical hosts only)
  become: True
  command: hwclock --systohc
  when: (ansible_virtualization_role == "host"
        or ansible_virtualization_role == "NA")
        and ansible_lsb.id != "Raspbian"
        and ansible_system_vendor != "DigitalOcean"
  listen: time configuration changed

